name: myproject_employee_attendance_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.4.0
  flutter_keyboard_visibility: ^5.4.0
  cloud_firestore: ^4.2.0
  font_awesome_flutter: ^10.3.0
  slide_to_act: ^2.0.1
  shared_preferences: ^2.0.17
  cupertino_icons: ^1.0.2
  month_year_picker: ^0.2.0+3
  intl: ^0.17.0
  location: ^4.4.0
  geocoding: ^2.0.5
  image_picker: ^0.8.6+1
  firebase_storage: ^11.0.10
  flutter_barcode_scanner: ^2.0.0
  
  
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
   
  fonts:
    - family: NexaBold
      fonts:
        - asset: assets/fonts/NexaBold.otf
    - family: NexaRegular
      fonts:
        - asset: assets/fonts/NexaRegular.otf
    - family: NexaLight
      fonts:
        - asset: assets/fonts/NexaLight.otf
 
